sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - /^v\d.*$/
    - master
    - development

php:
  - 5.6
  - 7.1

env:
  - WP_VERSION=4.4 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=trunk WP_MULTISITE=0

matrix:
  fast_finish: true
  exclude:
    - php: 7.1
      env: WP_VERSION=4.4 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=.dev/dev-lib
  - export DEV_LIB_SKIP=codeception,jscs,jshint,yuicompressor,phpunit
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git $DEV_LIB_PATH; fi
  - source $DEV_LIB_PATH/travis.install.sh
  - curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar > /tmp/wp-cli.phar
  - chmod +x /tmp/wp-cli.phar

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0' ]]; then composer require codeclimate/php-test-reporter --dev; fi
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0' ]]; then phpunit --coverage-clover build/logs/clover.xml; else phpunit; fi
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0' ]]; then ./vendor/bin/test-reporter; fi
  - source $DEV_LIB_PATH/travis.after_script.sh

before_deploy:
  - git submodule update --init
  - npm install
  - grunt "Run all development tasks."

deploy:
  provider: releases
  api_key: secure:RWNGTbIEiEOZgoLn6w1ggKzHBuMCht/nhIqoqoLFMFyBAao5CQd/vdUeyuhrOTjsgu9ki4qvXenNepL+D3ylVkrBtCLGDt2nj6TpaJLIuZWMWxkwGUnGBtkUSyeVeT+o42qjPh9gtfDat432yZWLU9sXUjVQ0fDuVbOVcFn3hRE=
  file: build/timeline-express-*.zip
  on:
    tags: true
    repo: EvanHerman/timeline-express
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
