sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      secure: MuZcXvlgysUkERhB3EiNMCcDtcD8un0jkcFR+wqYQtDfVIV4Lh1g7KBh0SGexuqdzqPCXoLMj29/aZg2j3J6FejjD5L+namXJOxUY58uYl04BF8Azz+7U8zkFcgp/N4byjKVNhrb0P9S6vtl/upU2Vzbyc0E9jUYQsNXOsr4abU=

branches:
  only:
  - "/^v\\d.*$/"
  - master
  - development

php:
  - 5.6
  - 7.1

services:
  - mysql

env:
- WP_VERSION=4.4 WP_MULTISITE=0
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=trunk WP_MULTISITE=0

matrix:
  fast_finish: true
  exclude:
  - php: 7.1
    env: WP_VERSION=4.4 WP_MULTISITE=0

install:
  - export DEV_LIB_PATH=.dev/dev-lib/scripts
  - export DEV_LIB_SKIP=codeception,jscs,jshint,yuicompressor,phpunit,xmllint
  - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname
    $( readlink .travis.yml ) ); fi
  - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/xwp/wp-dev-lib.git
    .dev/dev-lib; fi
  - source $DEV_LIB_PATH/travis.install.sh
  - curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli-nightly.phar
    > /tmp/wp-cli.phar
  - chmod +x /tmp/wp-cli.phar

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
    ]]; then composer require codeclimate/php-test-reporter --dev; fi
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
    ]]; then phpunit --coverage-clover build/logs/clover.xml; else phpunit; fi
  - if [[ $TRAVIS_PHP_VERSION = '7.1' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
    ]]; then ./vendor/bin/test-reporter; fi
  - source $DEV_LIB_PATH/travis.script.sh

after_script:
  - source $DEV_LIB_PATH/travis.after_script.sh
  - sudo service mysql stop

before_deploy:
  - git submodule update --init
  - npm install
  - grunt "Run all development tasks."

deploy:
  provider: releases
  api_key:
    secure: Z3/yLCyXNys/12ax0SHf4iQAGlq30CuybLwp5c/lglPBZIzOzQFmDh4CbaH9o2O7uKf6ZeVITBRCPFCSuhvTLpdm3e2aP01n7u5A5aPky5i5wqHG4qIFNn3nQeYZO5dF4OfMKap+Wx2dYflvumko0EhQJeZbxtnsPb9oQ1olzww=
  file_glob: true
  file: build/timeline-express-*.zip
  on:
    tags: true
    repo: EvanHerman/timeline-express
    php: '7.1'
    condition: "$WP_VERSION=trunk"
  skip_cleanup: true
  overwrite: true
